export GO_EASY_ON_ME=1

TOOL_NAME = assistantplus_root_helper
assistantplus_root_helper_INSTALL_PATH = /Applications/AssistantPlusApp.app
assistantplus_root_helper_OBJC_FILES = assistantplus_root_helper.c

include $(THEOS)/makefiles/common.mk
include $(THEOS)/makefiles/tool.mk
